name: npm-version-check
on:
  pull_request:
    branches:
      - master

jobs:
  npm-version-check:
    name: npm-version-check
    runs-on: ubuntu-latest
    steps:
      - name: Check Version
        uses: actions/checkout@v2
      - uses: kriasoft/check-version@v1
