name: npm-version-check
on:
  pull_request:
    branches:
      - master

jobs:
  npm-version-check:
    name: npm-version-check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Version Check
        id: check
        uses: EndBug/version-check@v2.0.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          file-url: https://unpkg.com/a-simple-migration-runner@latest/package.json
          static-checking: localIsNew

      - name: Log when changed
        if: steps.check.outputs.changed == 'true'
        run: 'echo "Version change found in commit ${{ steps.check.outputs.commit }}! New version: ${{ steps.check.outputs.version }} (${{ steps.check.outputs.type }})"'

      - name: Log when unchanged
        if: steps.check.outputs.changed == 'false'
        run: 'echo "No version change :/"'
